# Generated by Django 5.2.3 on 2025-06-17 18:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(editable=False, max_length=150, verbose_name='Логин для авторизации')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО курьера')),
                ('contact', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('vehicle_capacity_weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Грузоподъёмность (кг)')),
                ('vehicle_capacity_volume', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Объём багажника (м³)')),
                ('is_available', models.BooleanField(default=True, help_text='Если неактивен, заказы не будут назначаться этому курьеру', verbose_name='Доступен для доставки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('delivery_start', models.TimeField()),
                ('delivery_end', models.TimeField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=6)),
                ('contact', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('cluster', models.IntegerField(null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.courier', verbose_name='Назначенный курьер')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField(verbose_name='Номер кластера')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата маршрута')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='delivery.courier', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['courier', 'cluster'],
                'unique_together': {('courier', 'cluster')},
            },
        ),
        migrations.CreateModel(
            name='RouteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='Порядок следования')),
                ('status', models.CharField(blank=True, choices=[('delivered', 'Доставлен'), ('not_delivered', 'Не доставлен'), ('late', 'Опоздание')], max_length=20, verbose_name='Статус доставки')),
                ('courier_comment', models.TextField(blank=True, verbose_name='Комментарий курьера')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время фактической доставки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_items', to='delivery.order', verbose_name='Заказ')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Позиция маршрута',
                'verbose_name_plural': 'Позиции маршрута',
                'ordering': ['sequence'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
