# Generated by Django 5.2 on 2025-04-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_capacity_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vehicle_capacity_volume', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('delivery_start', models.TimeField()),
                ('delivery_end', models.TimeField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=6)),
                ('contact', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
