# Generated by Django 5.2 on 2025-04-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
