# Generated by Django 5.2 on 2025-04-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_order_id_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lon',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
