# Generated by Django 5.2 on 2025-04-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_order_lat_order_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
