# Generated by Django 5.2 on 2025-04-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_order_lat_alter_order_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
