# Generated by Django 5.2 on 2025-04-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_order_lat_alter_order_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cluster',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
