# Generated by Django 5.2 on 2025-04-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_order_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='name',
        ),
        migrations.AddField(
            model_name='courier',
            name='fio',
            field=models.CharField(default=1, max_length=255, verbose_name='ФИО курьера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courier',
            name='vehicle_capacity_volume',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Объём багажника (м³)'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='vehicle_capacity_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Грузоподъёмность (кг)'),
        ),
    ]
