# Generated by Django 5.2 on 2025-04-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_remove_courier_name_courier_fio_alter_courier_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couriers_available', models.PositiveIntegerField(default=0, verbose_name='Доступное количество курьеров')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
