# Generated by Django 5.2 on 2025-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_logisticsconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogisticsConfig',
        ),
        migrations.AddField(
            model_name='courier',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Если неактивен, заказы не будут назначаться этому курьеру', verbose_name='Доступен для доставки'),
        ),
    ]
