# Generated by Django 5.2 on 2025-04-21 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_delete_logisticsconfig_courier_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='contact',
            field=models.CharField(default=2, max_length=20, verbose_name='Контактный телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
