# Generated by Django 5.2 on 2025-04-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_courier_contact_courier_user_alter_courier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='user',
        ),
        migrations.AlterField(
            model_name='courier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
