# Generated by Django 5.2 on 2025-04-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_remove_courier_contact_remove_courier_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='contact',
            field=models.CharField(default=1, max_length=20, verbose_name='Контактный телефон'),
            preserve_default=False,
        ),
    ]
