# Generated by Django 5.2 on 2025-04-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_courier_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.courier', verbose_name='Назначенный курьер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cluster',
            field=models.IntegerField(null=True),
        ),
    ]
