# Generated by Django 5.2 on 2025-04-28 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_order_courier_alter_order_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField(verbose_name='Номер кластера')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='delivery.courier', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['courier', 'cluster'],
                'unique_together': {('courier', 'cluster')},
            },
        ),
        migrations.CreateModel(
            name='RouteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='Порядок следования')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_items', to='delivery.order', verbose_name='Заказ')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Позиция маршрута',
                'verbose_name_plural': 'Позиции маршрута',
                'ordering': ['sequence'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
