# Generated by Django 5.2 on 2025-04-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_route_routeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeitem',
            name='courier_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий курьера'),
        ),
        migrations.AddField(
            model_name='routeitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время фактической доставки'),
        ),
        migrations.AddField(
            model_name='routeitem',
            name='status',
            field=models.CharField(blank=True, choices=[('delivered', 'Доставлен'), ('not_delivered', 'Не доставлен'), ('late', 'Опоздание')], max_length=20, verbose_name='Статус доставки'),
        ),
    ]
