# Generated by Django 5.2 on 2025-04-29 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_routeitem_courier_comment_routeitem_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата маршрута'),
        ),
    ]
