# Generated by Django 5.2 on 2025-04-29 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_routeitem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeitem',
            name='date',
        ),
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата маршрута'),
        ),
    ]
