# Generated by Django 5.2 on 2025-05-01 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_remove_routeitem_date_route_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='login',
            field=models.CharField(default=1, editable=False, max_length=150, verbose_name='Логин для авторизации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
